DROP TABLE IF EXISTS "AgeAssessmentHistory" CASCADE;
DROP TABLE IF EXISTS "AgeAssessmentLesson" CASCADE;
DROP TABLE IF EXISTS "AgeLessonCompletion" CASCADE;
DROP TABLE IF EXISTS "AgePromotionAttempt" CASCADE;
DROP TABLE IF EXISTS "AgePromotionTest" CASCADE;
DROP TABLE IF EXISTS "StudentAgeAssessment" CASCADE;
DROP TABLE IF EXISTS "AssessmentAge" CASCADE;
DROP TABLE IF EXISTS "AdminLoginLog" CASCADE;

DROP TYPE IF EXISTS "PromotionOutcome";
DROP TYPE IF EXISTS "TuitionSubject";
